version: "3.8"

services:
  store-nginx:
    image: nginx:1.19.3-alpine
    container_name: store-nginx
    restart: always
    volumes:
        - ./html:/etc/nginx/html:ro
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - store-service
    ports:
      - "80:80"
  store-database:
    image: mysql:8.0.22
    container_name: store-database
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: toy
    volumes:
      - ./tearup/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
  shipping-gateway:
    image: andyrbell/mountebank:2.3.2
    volumes:
      - ./shipping-gateway/imposters.json:/imposters/imposters.json
    expose:
      - "8081"
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/imposters.json',
        '--allowInjection',
      ]
  payment-gateway:
    image: andyrbell/mountebank:2.3.2
    volumes:
      - ./payment-gateway/imposters.json:/imposters/imposters.json
    expose:
      - "8082"
    command:
      [
        'mb',
        'start',
        '--configfile',
        '/imposters/imposters.json',
        '--allowInjection',
      ]
  store-service:
    image: toonhudsha/toy-store-service:0.0.1
    build: 
      context: store-service
    container_name: store-service
    ports:
      - '8000:8000'
    depends_on:
      - store-database
    restart: always
    environment: 
      - TEST_MODE=true
      - BANK_GATEWAY=http://payment-gateway:8082
      - SHIPPING_GATEWAY=http://shipping-gateway:8081
      - DBCONNECTION=root:password@(store-database:3306)/toy
  